version: '3.3'
services:
  mariadb:
    image: 'bitnami/mariadb:latest'
    labels:
      kompose.service.type: nodeport
    ports:
      - '3306:3306'
    volumes:
      - 'mariadb_data:/bitnami'
    environment:
      - MARIADB_USER=testuser
      - MARIADB_PASSWORD=mypwd
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_DATABASE=mydb
volumes:
  mariadb_data:
    driver: local
